volumes:
  vol_node_modules:
  vol_dist:
services:
  node:
    environment:
      - TZ=Asia/Tokyo
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - vol_node_modules:/app/node_modules
      - vol_dist:/app/dist
      - .:/app
    command: [ "ash", "-c", "yarn build && yarn start" ]
